version: 2.1

commands:
  print_pipeline_id:
    description: "A very simple command for demonstration purposes"
    steps:
      - run: return 1
      - run:
        name: HANDLE_FAIL
        command: echo "FAILED LAST STEP"
        when: on_fail

workflows:
  version: 2
  build:
    jobs:
      - test

jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml

  test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - print_pipeline_id
